name: CI
on: [pull_request]

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - run: make lint

  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - run: make test
        env:
          DOCKER_TOOLS: false